# Generated by Django 5.1 on 2024-08-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/receipts/'),
        ),
    ]
