# Generated by Django 5.1 on 2024-08-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_user_idscan_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='IDscan',
        ),
    ]
