# Generated by Django 5.1 on 2024-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0004_remove_user_idscan"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="shaba",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
